[package]
name = "arbiter-config"
version = "1.1.0"
edition = "2021"

[dependencies]
jsonschema = "0.37.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
thiserror = "2.0.17"
